#!/bin/bash

#!/bin/bash

PIN=19
LED_STA=10

trap ctrl_c INT
function ctrl_c() {
    echo "go away by default"
    if [[ -d /sys/class/gpio/gpio$PIN ]]; then
        echo $PIN >/sys/class/gpio/unexport
    fi
    exit 0
}

raspi-gpio set $PIN ip pu
raspi-gpio set $LED_STA op

if [[ ! -d /sys/class/gpio/gpio$PIN ]]; then
    echo $PIN >/sys/class/gpio/export
fi

while true; do
	raspi-gpio set $LED_STA dl
	
    # wait for gpio pull and check network
    while [[ $(cat /sys/class/gpio/gpio$PIN/value) == "1" ]]; do
        if [[ ! $(iwgetid -r) ]]; then
            raspi-gpio set $LED_STA dl
        fi
        sleep 0.5s
        raspi-gpio set $LED_STA dh
        sleep 0.5s
    done

    echo "go to ap"
    raspi-gpio set $LED_STA op dl
    switch-ap
    raspi-gpio set $LED_STA dh

    # wait for gpio release
    while [[ $(cat /sys/class/gpio/gpio$PIN/value) == "0" ]]; do
        raspi-gpio set $LED_STA dh
        sleep 0.1s
        raspi-gpio set $LED_STA dl
        sleep 0.4s
    done
    echo "go to station mode"
    raspi-gpio set $LED_STA dl
    switch-sta
    


done
